name: Playwright Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache node_modules
        uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install node_modules
        run: yarn install
      
      # - name: Install Playwright browsers
      #   run: npx playwright install --with-deps

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright
      
      - name: Cache FE build
        uses: actions/cache@v4
        id: build-cache
        with:
          path: |
            build
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Create FE build
        run: yarn build:ci

      - name: Start application and tests
        run: |
          yarn start:ci &
          sleep 5 &&
          curl http://localhost:3000 &&
          npx playwright test
        env:
          SEED_USERBASE_SIZE: 5
          SEED_CONTACTS_PER_USER: 3
          SEED_PAYMENTS_PER_USER: 15
          SEED_REQUESTS_PER_USER: 10
          SEED_BANK_ACCOUNTS_PER_USER: 1
          SEED_LIKES_PER_USER: 2
          SEED_COMMENTS_PER_USER: 2
          SEED_NOTIFICATIONS_PER_USER: 5
          SEED_BANK_TRANSFERS_PER_USER: 5
          SEED_DEFAULT_USER_PASSWORD: s3cret
          PAGINATION_PAGE_SIZE: 10
          PORT: 3000
          VITE_BACKEND_PORT: 3001
          BACKEND_PORT: 3001
