name: Playwright Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:focal
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: build

  playwright-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:focal
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Run Playwright Tests - ${{ matrix.browser }}
        run: npx playwright test --project=${{ matrix.browser }}
        env:
          PLAYWRIGHT_BROWSER_NAME: ${{ matrix.browser }}

  playwright-mobile-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:focal
      options: --user 1001
    needs: install
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Run Playwright Mobile Tests - ${{ matrix.browser }}
        run: npx playwright test --project=${{ matrix.browser }} --config=playwright.mobile.config.ts
        env:
          PLAYWRIGHT_BROWSER_NAME: ${{ matrix.browser }}
